### PR TITLE
Redux actions

### PR DESCRIPTION
**Pull request by stanleySimeon**
# In this milestone I:

  - installed Redux
  - add redux to the project
  -

### CODE REVIEW

**Review by AnselemOdims — CHANGES_REQUESTED** [review]
### Hi @stanleySimeon , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Redux is not set up in the project, please ensure you install and configure redux. Also,
   - react-redux should be present in package.json
   - The structure of the files should follow the `ducks pattern`
   - The `configureStore.js`, `books.js`, and `categories.js` should be set up properly in the redux folder.
 - [ ] Please also kindly check the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/add_reducers_an_actions.md) properly and ensure that all requirements are met.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by stanleySimeon** [comment]
okay

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @stanleySimeon 👋, 

Great work attempting to implement the changes suggested by a previous reviewer 👏  

You tried to implement the requested changes, but there are still some which aren't been addressed yet.


 ## Required Changes ♻️
#### I am making these comments here because I can't highlight the necessary pieces of codes in the **_files changed_** section. 

Kindly implement the following changes based on the last reviewer's request:
- Kindly install react-redux as a dependency. To install react-redux, you can run the following command `npm install redux react-redux`.
- Kindly structure your redux file using the duck pattern. To learn more about the duck pattern, you can read this [article](https://github.com/erikras/ducks-modular-redux). _**Hint**_:

image

- Kindly set up your actions, action creators, and reducers for both the Book and Categories components. Also, you forgot to set up the store. You can read this [article](https://www.geeksforgeeks.org/introduction-to-redux-action-reducers-and-store/) to have an idea of how to implement this change. 👍 

## Optional suggestions
- Kindly populate this section of your README.md file with the necessary instructions. This will make your `README.md` file very professional. 👍 

image


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stanleySimeon** [comment]
So where is the problem?

**Comment by stanleySimeon** [comment]
This my dependency
I have redux on it

**Review by keroloussamy — COMMENTED** [review]
Hi @stanleySimeon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

clap


## Note that you can't merge before your project is accepted.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stanleySimeon** [comment]
This is the structure of my redux folder

**Comment by stanleySimeon** [comment]
what I have to remove or add on it

**Pull request merged**
